---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  become: true

- name: Copy /etc/hostname
  copy:
    content: "{{ inventory_hostname_short }}{{ '\n' }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  become: true
