---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: molecule-ubuntu-hostname
    image: ubuntu
    image_version: 16.04
    cap_add:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
